"""
ANE-backed autoresearch training loop.

This is a pragmatic Mac fork of upstream autoresearch:
- Training runs through maderix/ANE's dynamic trainer.
- Evaluation happens in Python from the emitted checkpoint.
- The validation metric is ANE-local: shorter context + smaller eval budget so
  runs stay practical on Apple Silicon laptops.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import re
import resource
import struct
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from prepare import CACHE_DIR, get_token_bytes

TIME_BUDGET_SECONDS = 300

# Model architecture
ASPECT_RATIO = 48
HEAD_DIM = 64
DEPTH = 8
HIDDEN_DIM_MULTIPLE = 128

# ANE runner
ANE_SEQ_LEN = 256
ANE_ACCUM_STEPS = 10
ANE_LR = 3e-4
ANE_WARMUP_STEPS = 100
ANE_GRAD_CLIP = 1.0
ANE_CALIBRATION_STEPS = 200

# Validation
ANE_EVAL_SEQ_LEN = 256
ANE_EVAL_TOKENS = 65_536
ANE_EVAL_BATCH_SIZE_MPS = 2
ANE_EVAL_BATCH_SIZE_CPU = 1

ANE_CACHE_DIR = Path(CACHE_DIR) / "ane"
MANIFEST_PATH = ANE_CACHE_DIR / "manifest.json"
BUILD_DIR = ANE_CACHE_DIR / "build"
LOG_PATH = ANE_CACHE_DIR / "train_ane.log"
HEADER_STRUCT = struct.Struct("<10i2f3d6i")


@dataclass(frozen=True)
class ModelConfig:
    vocab_size: int
    n_layer: int
    dim: int
    hidden_dim: int
    n_head: int
    n_kv_head: int
    head_dim: int
    seq_len: int

    @property
    def q_dim(self) -> int:
        return self.n_head * self.head_dim

    @property
    def kv_dim(self) -> int:
        return self.n_kv_head * self.head_dim

    @property
    def ckpt_stem(self) -> str:
        return (
            f"ane_d{self.n_layer}_dim{self.dim}_hid{self.hidden_dim}_"
            f"h{self.n_head}_hd{self.head_dim}_v{self.vocab_size}_s{self.seq_len}"
        )

    @property
    def num_params(self) -> int:
        per_layer = (
            self.q_dim * self.dim
            + self.kv_dim * self.dim
            + self.kv_dim * self.dim
            + self.dim * self.q_dim
            + self.hidden_dim * self.dim
            + self.dim * self.hidden_dim
            + self.hidden_dim * self.dim
            + 2 * self.dim
        )
        return self.vocab_size * self.dim + self.dim + self.n_layer * per_layer


@dataclass(frozen=True)
class CheckpointHeader:
    magic: int
    version: int
    step: int
    total_steps: int
    n_layers: int
    vocab_size: int
    dim: int
    hidden_dim: int
    n_heads: int
    seq_len: int
    lr: float
    loss: float
    cum_compile: float
    cum_train: float
    cum_wall: float
    cum_steps: int
    cum_batches: int
    adam_t: int
    kv_heads: int
    head_dim: int
    q_dim: int


def round_up(value: int, multiple: int) -> int:
    return ((value + multiple - 1) // multiple) * multiple


def build_model_config(vocab_size: int) -> ModelConfig:
    dim = round_up(DEPTH * ASPECT_RATIO, HEAD_DIM)
    n_head = dim // HEAD_DIM
    hidden_dim = round_up(int(math.ceil((8 * dim) / 3)), HIDDEN_DIM_MULTIPLE)
    return ModelConfig(
        vocab_size=vocab_size,
        n_layer=DEPTH,
        dim=dim,
        hidden_dim=hidden_dim,
        n_head=n_head,
        n_kv_head=n_head,
        head_dim=HEAD_DIM,
        seq_len=ANE_SEQ_LEN,
    )


def locate_ane_repo() -> Path:
    candidates = []
    env_ane_home = os.environ.get("ANE_HOME")
    if env_ane_home:
        candidates.append(Path(env_ane_home))
    candidates.extend(
        [
            Path.cwd().parent / "ANE",
            Path("/tmp/ANE"),
            Path.cwd() / "vendor" / "ANE",
        ]
    )
    for candidate in candidates:
        train_source = candidate / "training" / "training_dynamic" / "train.m"
        if train_source.exists():
            return candidate
    searched = "\n".join(f"- {candidate}" for candidate in candidates)
    raise SystemExit(
        "Could not locate the ANE repository.\n"
        "Set ANE_HOME or clone https://github.com/maderix/ANE into one of:\n"
        f"{searched}"
    )


def load_manifest() -> dict[str, object]:
    if not MANIFEST_PATH.exists():
        raise SystemExit(
            f"ANE token cache is missing at {MANIFEST_PATH}.\n"
            "Run `uv run prepare.py` and then `uv run prepare_ane.py` first."
        )
    return json.loads(MANIFEST_PATH.read_text())


def shell(command: list[str], cwd: Path | None = None, capture_output: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=cwd,
        check=True,
        text=True,
        capture_output=capture_output,
    )


def header_literal(path: Path) -> str:
    return str(path).replace("\\", "\\\\").replace('"', '\\"')


def generate_model_header(config: ModelConfig, train_tokens_path: Path, ckpt_path: Path) -> str:
    return f"""// Autogenerated by train_ane.py
#pragma once
#define MODEL_NAME "AutoresearchANE"

#define DIM {config.dim}
#define HIDDEN {config.hidden_dim}
#define HEADS {config.n_head}
#define KV_HEADS {config.n_kv_head}
#define HD {config.head_dim}
#define GQA_RATIO (HEADS / KV_HEADS)
#define Q_DIM (HEADS * HD)
#define KV_DIM (KV_HEADS * HD)
#define SEQ {config.seq_len}
#define NLAYERS {config.n_layer}
#define VOCAB {config.vocab_size}

#define CKPT_PATH "{header_literal(ckpt_path)}"
#define DEFAULT_DATA_PATH "{header_literal(train_tokens_path)}"
"""


def compile_ane_binary(ane_home: Path, config: ModelConfig, train_tokens_path: Path, ckpt_path: Path) -> tuple[Path, Path]:
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    source_path = ane_home / "training" / "training_dynamic" / "train.m"
    header_path = BUILD_DIR / f"{config.ckpt_stem}.h"
    binary_path = BUILD_DIR / f"{config.ckpt_stem}.train"

    header_text = generate_model_header(config, train_tokens_path, ckpt_path)
    header_path.write_text(header_text)

    if binary_path.exists() and binary_path.stat().st_mtime >= max(source_path.stat().st_mtime, header_path.stat().st_mtime):
        return header_path, binary_path

    sdk_path = shell(["xcrun", "--show-sdk-path"], capture_output=True).stdout.strip()
    command = [
        "xcrun",
        "clang",
        "-O2",
        "-DACCELERATE_NEW_LAPACK",
        "-framework",
        "Foundation",
        "-framework",
        "IOSurface",
        "-framework",
        "Accelerate",
        "-isysroot",
        sdk_path,
        "-fobjc-arc",
        "-include",
        str(header_path),
        "-o",
        str(binary_path),
        str(source_path),
    ]
    shell(command, cwd=source_path.parent)
    return header_path, binary_path


def parse_training_log(log_text: str) -> dict[str, float | int]:
    patterns = {
        "steps": r"Total steps:\s+(\d+)",
        "compile_ms": r"Compile:\s+([0-9.]+)ms",
        "train_ms": r"Train time:\s+([0-9.]+)ms",
        "train_ms_per_step": r"Train time:\s+[0-9.]+ms \(([0-9.]+)ms/step\)",
        "wall_s": r"Wall time:\s+([0-9.]+)s",
    }
    parsed: dict[str, float | int] = {}
    for key, pattern in patterns.items():
        match = re.search(pattern, log_text)
        if match:
            value = float(match.group(1))
            parsed[key] = int(value) if key == "steps" else value
    return parsed


def run_ane_training(
    binary_path: Path,
    train_tokens_path: Path,
    steps: int,
    lr: float,
) -> dict[str, float | int]:
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    command = [
        str(binary_path),
        "--scratch",
        "--steps",
        str(steps),
        "--lr",
        str(lr),
        "--accum",
        str(ANE_ACCUM_STEPS),
        "--warmup",
        str(ANE_WARMUP_STEPS),
        "--clip",
        str(ANE_GRAD_CLIP),
        "--data",
        str(train_tokens_path),
    ]
    with LOG_PATH.open("w") as log_file:
        subprocess.run(
            command,
            cwd=binary_path.parent,
            check=True,
            text=True,
            stdout=log_file,
            stderr=subprocess.STDOUT,
        )
    log_text = LOG_PATH.read_text()
    parsed = parse_training_log(log_text)
    if "steps" not in parsed:
        tail = "\n".join(log_text.splitlines()[-40:])
        raise RuntimeError(f"ANE trainer did not finish cleanly.\nLast log lines:\n{tail}")
    return parsed


def steps_for_time_budget(
    binary_path: Path,
    train_tokens_path: Path,
    lr: float,
    time_budget_seconds: float,
    calibration_steps: int,
) -> int:
    calibration = run_ane_training(binary_path, train_tokens_path, calibration_steps, lr)
    train_ms_per_step = float(calibration["train_ms_per_step"])
    estimated_steps = max(100, int((time_budget_seconds * 1000.0) / train_ms_per_step))
    # The ANE trainer only checkpoints every 100 steps, so keep runs aligned to that cadence.
    return max(100, (estimated_steps // 100) * 100)


def select_eval_device() -> tuple[torch.device, int]:
    if torch.backends.mps.is_available():
        return torch.device("mps"), ANE_EVAL_BATCH_SIZE_MPS
    return torch.device("cpu"), ANE_EVAL_BATCH_SIZE_CPU


def read_float_array(handle, count: int, shape: tuple[int, ...] | None = None) -> np.ndarray:
    array = np.fromfile(handle, dtype=np.float32, count=count)
    if array.size != count:
        raise EOFError(f"Checkpoint ended early while reading {count} floats")
    if shape is not None:
        array = array.reshape(shape)
    return array


def load_checkpoint(ckpt_path: Path) -> tuple[CheckpointHeader, dict[str, object]]:
    with ckpt_path.open("rb") as handle:
        header = CheckpointHeader(*HEADER_STRUCT.unpack(handle.read(HEADER_STRUCT.size)))
        if header.magic != 0x424C5A54 or header.version != 4:
            raise ValueError(f"Unsupported ANE checkpoint header: magic={header.magic:#x}, version={header.version}")

        q_dim = header.q_dim
        kv_dim = header.kv_heads * header.head_dim
        dim = header.dim
        hidden_dim = header.hidden_dim

        layer_weights = []
        layer_params = (
            q_dim * dim,
            kv_dim * dim,
            kv_dim * dim,
            dim * q_dim,
            hidden_dim * dim,
            dim * hidden_dim,
            hidden_dim * dim,
            dim,
            dim,
        )
        skip_per_layer = 2 * sum(layer_params)

        for _ in range(header.n_layers):
            layer_weights.append(
                {
                    "Wq": read_float_array(handle, q_dim * dim, (q_dim, dim)),
                    "Wk": read_float_array(handle, kv_dim * dim, (kv_dim, dim)),
                    "Wv": read_float_array(handle, kv_dim * dim, (kv_dim, dim)),
                    "Wo": read_float_array(handle, dim * q_dim, (dim, q_dim)),
                    "W1": read_float_array(handle, hidden_dim * dim, (hidden_dim, dim)),
                    "W2": read_float_array(handle, dim * hidden_dim, (dim, hidden_dim)),
                    "W3": read_float_array(handle, hidden_dim * dim, (hidden_dim, dim)),
                    "rms_att": read_float_array(handle, dim),
                    "rms_ffn": read_float_array(handle, dim),
                }
            )
            handle.seek(skip_per_layer * 4, os.SEEK_CUR)

        rms_final = read_float_array(handle, dim)
        handle.seek(2 * dim * 4, os.SEEK_CUR)
        embed = read_float_array(handle, header.vocab_size * dim, (header.vocab_size, dim))

    payload = {
        "layers": layer_weights,
        "rms_final": rms_final,
        "embed": embed,
    }
    return header, payload


def peak_memory_mb() -> float:
    ru_maxrss = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    if sys.platform == "darwin":
        return ru_maxrss / (1024 * 1024)
    return ru_maxrss / 1024


class RMSNorm(nn.Module):
    def __init__(self, weight: np.ndarray, eps: float = 1e-5):
        super().__init__()
        self.eps = eps
        self.register_buffer("weight", torch.from_numpy(weight.copy()))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        variance = x.pow(2).mean(dim=-1, keepdim=True)
        x = x * torch.rsqrt(variance + self.eps)
        return x * self.weight


class ANESelfAttention(nn.Module):
    def __init__(self, config: ModelConfig, layer_state: dict[str, np.ndarray]):
        super().__init__()
        self.n_head = config.n_head
        self.n_kv_head = config.n_kv_head
        self.head_dim = config.head_dim
        self.register_buffer("wq", torch.from_numpy(layer_state["Wq"].copy()))
        self.register_buffer("wk", torch.from_numpy(layer_state["Wk"].copy()))
        self.register_buffer("wv", torch.from_numpy(layer_state["Wv"].copy()))
        self.register_buffer("wo", torch.from_numpy(layer_state["Wo"].copy()))

    def _apply_rope(self, x: torch.Tensor) -> torch.Tensor:
        _, _, seq_len, head_dim = x.shape
        half_dim = head_dim // 2
        positions = torch.arange(seq_len, device=x.device, dtype=torch.float32)
        freq = torch.arange(half_dim, device=x.device, dtype=torch.float32)
        freq = 1.0 / (10000 ** (2 * freq / head_dim))
        angles = torch.outer(positions, freq)
        cos = angles.cos()[None, None, :, :]
        sin = angles.sin()[None, None, :, :]
        x_even = x[..., 0::2]
        x_odd = x[..., 1::2]
        rotated_even = x_even * cos - x_odd * sin
        rotated_odd = x_even * sin + x_odd * cos
        return torch.stack((rotated_even, rotated_odd), dim=-1).reshape_as(x)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        batch_size, seq_len, _ = x.shape
        q = F.linear(x, self.wq).view(batch_size, seq_len, self.n_head, self.head_dim).transpose(1, 2)
        k = F.linear(x, self.wk).view(batch_size, seq_len, self.n_kv_head, self.head_dim).transpose(1, 2)
        v = F.linear(x, self.wv).view(batch_size, seq_len, self.n_kv_head, self.head_dim).transpose(1, 2)
        q = self._apply_rope(q)
        k = self._apply_rope(k)
        if self.n_kv_head != self.n_head:
            repeat = self.n_head // self.n_kv_head
            k = k.repeat_interleave(repeat, dim=1)
            v = v.repeat_interleave(repeat, dim=1)
        scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(self.head_dim)
        causal_mask = torch.triu(
            torch.full((seq_len, seq_len), float("-inf"), device=x.device, dtype=scores.dtype),
            diagonal=1,
        )
        scores = scores + causal_mask
        probs = scores.softmax(dim=-1)
        attn = torch.matmul(probs, v)
        attn = attn.transpose(1, 2).contiguous().view(batch_size, seq_len, self.n_head * self.head_dim)
        return F.linear(attn, self.wo)


class ANEFFN(nn.Module):
    def __init__(self, layer_state: dict[str, np.ndarray]):
        super().__init__()
        self.register_buffer("w1", torch.from_numpy(layer_state["W1"].copy()))
        self.register_buffer("w2", torch.from_numpy(layer_state["W2"].copy()))
        self.register_buffer("w3", torch.from_numpy(layer_state["W3"].copy()))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        h1 = F.linear(x, self.w1)
        h3 = F.linear(x, self.w3)
        gated = F.silu(h1) * h3
        return F.linear(gated, self.w2)


class ANEBlock(nn.Module):
    def __init__(self, config: ModelConfig, layer_state: dict[str, np.ndarray], res_alpha: float):
        super().__init__()
        self.res_alpha = res_alpha
        self.attn_norm = RMSNorm(layer_state["rms_att"])
        self.ffn_norm = RMSNorm(layer_state["rms_ffn"])
        self.attn = ANESelfAttention(config, layer_state)
        self.ffn = ANEFFN(layer_state)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x2 = x + self.res_alpha * self.attn(self.attn_norm(x))
        return x2 + self.res_alpha * self.ffn(self.ffn_norm(x2))


class ANETransformer(nn.Module):
    def __init__(self, config: ModelConfig, checkpoint: dict[str, object]):
        super().__init__()
        self.config = config
        self.res_alpha = 1.0 / math.sqrt(2.0 * config.n_layer)
        embed = torch.from_numpy(np.asarray(checkpoint["embed"]).copy())
        self.register_buffer("embed", embed)
        self.final_norm = RMSNorm(np.asarray(checkpoint["rms_final"]))
        self.layers = nn.ModuleList(
            [ANEBlock(config, layer_state, self.res_alpha) for layer_state in checkpoint["layers"]]
        )

    def forward(self, idx: torch.Tensor, targets: torch.Tensor | None = None, reduction: str = "mean") -> torch.Tensor:
        x = F.embedding(idx, self.embed)
        for layer in self.layers:
            x = layer(x)
        x = self.final_norm(x)
        logits = F.linear(x, self.embed).float()
        if targets is None:
            return logits
        return F.cross_entropy(
            logits.view(-1, logits.size(-1)),
            targets.view(-1),
            ignore_index=-1,
            reduction=reduction,
        )


def val_token_loader(token_path: Path, batch_size: int, seq_len: int):
    tokens = np.memmap(token_path, dtype=np.uint16, mode="r")
    if tokens.size < batch_size * (seq_len + 1):
        raise ValueError(
            f"Validation token stream at {token_path} only has {tokens.size:,} tokens; "
            f"need at least {batch_size * (seq_len + 1):,}."
        )

    stride = batch_size * seq_len
    max_pos = tokens.size - batch_size * (seq_len + 1)
    pos = 0
    while True:
        if pos > max_pos:
            pos = 0
        window = np.asarray(tokens[pos : pos + batch_size * (seq_len + 1)], dtype=np.int64)
        batch = window.reshape(batch_size, seq_len + 1)
        yield torch.from_numpy(batch[:, :-1]), torch.from_numpy(batch[:, 1:])
        pos += stride


@torch.no_grad()
def evaluate_bpb_lite(
    model: ANETransformer,
    val_tokens_path: Path,
    eval_tokens: int,
    seq_len: int,
) -> float:
    device, batch_size = select_eval_device()
    model.to(device)
    model.eval()
    loader = val_token_loader(val_tokens_path, batch_size, seq_len)
    token_bytes = get_token_bytes(device="cpu").to(device)
    steps = max(1, eval_tokens // (batch_size * seq_len))
    total_nats = 0.0
    total_bytes = 0.0
    for _ in range(steps):
        x, y = next(loader)
        x = x.to(device)
        y = y.to(device)
        loss_flat = model(x, y, reduction="none").view(-1)
        y_flat = y.view(-1)
        nbytes = token_bytes[y_flat]
        mask = nbytes > 0
        total_nats += float((loss_flat * mask).sum().item())
        total_bytes += float(nbytes.sum().item())
    return total_nats / (math.log(2) * total_bytes)


def validate_platform() -> None:
    if sys.platform != "darwin":
        raise SystemExit("ANE mode requires macOS.")
    if os.uname().machine != "arm64":
        raise SystemExit("ANE mode requires Apple Silicon.")


def main() -> None:
    parser = argparse.ArgumentParser(description="ANE-backed autoresearch run")
    parser.add_argument("--skip-train", action="store_true", help="Skip ANE training and only evaluate the latest checkpoint")
    parser.add_argument("--steps", type=int, default=None, help="Override ANE training steps directly")
    parser.add_argument("--lr", type=float, default=ANE_LR, help=f"Override ANE learning rate (default: {ANE_LR})")
    parser.add_argument(
        "--time-budget",
        type=float,
        default=TIME_BUDGET_SECONDS,
        help=f"Training-time budget in seconds when --steps is not provided (default: {TIME_BUDGET_SECONDS})",
    )
    parser.add_argument(
        "--calibration-steps",
        type=int,
        default=ANE_CALIBRATION_STEPS,
        help=f"Short calibration run used to estimate steps for the time budget (default: {ANE_CALIBRATION_STEPS})",
    )
    parser.add_argument(
        "--eval-tokens",
        type=int,
        default=ANE_EVAL_TOKENS,
        help=f"Override ANE validation token budget (default: {ANE_EVAL_TOKENS})",
    )
    args = parser.parse_args()

    validate_platform()
    manifest = load_manifest()
    ane_home = locate_ane_repo()
    train_tokens_path = Path(manifest["train"]["path"])
    val_tokens_path = Path(manifest["val"]["path"])
    vocab_size = int(manifest["vocab_size"])
    config = build_model_config(vocab_size)
    ckpt_path = BUILD_DIR / f"{config.ckpt_stem}.bin"

    t_start = time.time()
    _, binary_path = compile_ane_binary(ane_home, config, train_tokens_path, ckpt_path)

    train_stats = {"steps": 0, "train_ms": 0.0, "wall_s": 0.0}
    if not args.skip_train:
        target_steps = args.steps
        if target_steps is None:
            target_steps = steps_for_time_budget(
                binary_path,
                train_tokens_path,
                args.lr,
                args.time_budget,
                args.calibration_steps,
            )
            print(f"Calibrated step budget: {target_steps} steps for ~{args.time_budget:.0f}s of training")
        train_stats = run_ane_training(binary_path, train_tokens_path, target_steps, args.lr)

    if not ckpt_path.exists():
        raise SystemExit(
            f"ANE checkpoint not found at {ckpt_path}.\n"
            "The trainer only saves on checkpoint intervals after a finite best loss."
        )

    header, checkpoint = load_checkpoint(ckpt_path)
    model = ANETransformer(config, checkpoint)
    val_bpb = evaluate_bpb_lite(model, val_tokens_path, args.eval_tokens, ANE_EVAL_SEQ_LEN)

    total_seconds = time.time() - t_start
    total_tokens = int(train_stats.get("steps", 0)) * config.seq_len

    print("---")
    print(f"val_bpb:          {val_bpb:.6f}")
    print(f"training_seconds: {float(train_stats.get('train_ms', 0.0)) / 1000:.1f}")
    print(f"total_seconds:    {total_seconds:.1f}")
    print(f"peak_vram_mb:     {peak_memory_mb():.1f}")
    print("mfu_percent:      0.00")
    print(f"total_tokens_M:   {total_tokens / 1e6:.1f}")
    print(f"num_steps:        {int(train_stats.get('steps', 0))}")
    print(f"num_params_M:     {config.num_params / 1e6:.1f}")
    print(f"depth:            {header.n_layers}")


if __name__ == "__main__":
    main()
